import type { Metadata } from "next";
import { SectionLabel } from "@/components/ui/SectionLabel";

export const metadata: Metadata = { title: "For creators", description: "How PCBOD could let PCB designers publish physical products without holding inventory." };

const files = ["plantbrain.kicad_pcb", "gerbers.zip", "BOM.csv", "CPL.csv", "firmware.bin", "README.md"];
export default function ForCreatorsPage() {
  return <main><section className="technical-grid border-b border-line"><div className="mx-auto max-w-[1200px] px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><SectionLabel>For PCB creators</SectionLabel><h1 className="max-w-4xl text-5xl font-black tracking-[-0.05em] text-ink sm:text-6xl">Build the board. Publish the product. Keep inventory off your desk.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-graphite">PCBOD’s creator concept turns a production-ready PCB package into a reviewed, revisioned product listing that can be manufactured after demand appears.</p></div></section><section className="mx-auto max-w-[1200px] px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><div><SectionLabel>Concept publishing flow</SectionLabel><ol className="space-y-3">{["Create product draft","Upload production + buyer files","Choose protected or open distribution","Submit revision for review","Publish approved revision","Royalty recorded on eligible orders"].map((x,i)=><li key={x} className="flex gap-4 border border-line bg-cream p-4"><span className="font-mono text-[10px] text-copper">0{i+1}</span><span className="font-semibold text-ink">{x}</span></li>)}</ol></div><div className="border border-line bg-solder p-6 text-white"><div className="font-mono text-[10px] uppercase tracking-[.15em] text-white/60">Manufacturing package / example</div><div className="mt-6 divide-y divide-white/10 border-y border-white/10">{files.map((file,i)=><div key={file} className="flex items-center justify-between py-3 font-mono text-xs"><span>{file}</span><span className={i<4?"text-brass":"text-white/50"}>{i<4?"PRODUCTION":"BUYER-SAFE"}</span></div>)}</div><div className="mt-6 border border-white/15 bg-white/[.04] p-4 text-sm leading-6 text-white/70">Protected manufacturing files are intended to stay outside the public purchase flow unless the creator explicitly chooses an open distribution mode.</div></div></div></section></main>;
}
